version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_UID:
        USER_GID:
    init: true
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    #ports:
    #  - 8000:8000

volumes:
  node_modules:
